### ISSUE TITLE
3D Printing Housing for Raspberry Pi

### ISSUE THREAD

**Issue by AndreasVerden** [DarwinAutomations/lupus2#5]
The model for the housing has already been designed. Now we need to print it.

The housing doesn't need to be very robust, using PLA should suffice.

**Comment by WimZimmermann** [comment]
Due to problems with our "manufacturer" we won't be able to complete this task in this sprint. We are working on a solution and already decided to buy a 3D printer (CR-10). Will be delivered in 15-20 days.
To be continued...
